---
name: C++ Build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v2
    - name: Install Clang
      run: sudo apt install clang
    - name: Build
      run: for d in $(find $GITHUB_WORKSPACE/*/* -maxdepth 1 -type d); do clang++ $d/*.cpp -o $d/test_build -std=c++17 -Werror; done;
